### ISSUE TITLE
Chokes when creating a mask

### ISSUE THREAD

**Issue by 3zzy** [Turfjs/turf#1454]
Turf seems to choke on this particular GeoJSON (converted from Shapefile) when creating a mask:

http://jsfiddle.net/4ekd3o1t/

Is it the conversion or something else that causing the issue?

**Comment by rowanwins** [comment]
Hi @3zzy 

Any chance you can just post the geojson object a gist - jsfiddle just keeps crashing on me so I can't properly look at the geojson object you're passing in.

I'm currently reworking the `mask` module as part of some changes for v7 of Turf so I'll likely look at this as part of that.

Cheers
Rowan

**Comment by 3zzy** [comment]
@rowanwins Sure, here you go: https://gist.github.com/3zzy/1b589e857c122a114d7856c4de14f04b

**Comment by 3zzy** [comment]
@rowanwins  In the meantime, I'm trying to create a mask using intersect but it doesn't seem to work either:

```
geojson = turf.featureReduce(geojson, function (previousValue, currentFeature, featureIndex) {
	var currentFeatureMask = turf.mask(currentFeature);
	if (!!previousValue && !!currentFeatureMask) {
		mask = turf.intersect(previousValue, currentFeatureMask);		
	}
	else {
		mask = currentFeatureMask;
	}
  return mask;
});
```
Fiddle: http://jsfiddle.net/oc86g2j4/42/

What am I doing wrong? 

Thanks!

**Comment by rowanwins** [comment]
Hi @3zzy 

I suspect your issue is that your passing in a feature collection of polygons rather than a polygon or multi-polygon, haven't double checked but suspect that's whats going on. My new version will cater for passing in feature collections or single features.

**Comment by 3zzy** [comment]
@rowanwins  I did try 'combine' and 'flatten' which I believe convert its to a MultiPolygon but when creating a mask it still freezes.

**Comment by rowanwins** [comment]
Ok well ive addedit as test in the new unreleased version and its now working so I'll let you know when it's available for use

**Comment by 3zzy** [comment]
@rowanwins Oh great, where can I get the unreleased version? Needed this layer to work for a demo on Tuesday. Thanks!

**Comment by rowanwins** [comment]
The v7 branch, its still a work in progress. Or you might also have luck with this [pull request](https://github.com/Turfjs/turf/pull/1456)

**Comment by 3zzy** [comment]
@rowanwins Is there any ETA for the release?

**Comment by rowanwins** [comment]
Fingers crossed it'll be out as an alpha sometime this week.

**Comment by 3zzy** [comment]
@rowanwins v7.0.0 milestone is complete, release it already! ;)

**Comment by 3zzy** [comment]
@rowanwins I just tried the same layer with v7 and looks like the issue not resolved. Have you tested it with the specific GeoJSON I'm having issue with?

**Comment by 3zzy** [comment]
July 2020 and still having same issue. I can see that there is some activity but no releases since 2016 which is so sad :(

**Comment by rowanwins** [comment]
Hi @3zzy 

We just published v6.2.0-alpha.2 last week, can you give that a go?

https://www.npmjs.com/package/@turf/mask/v/6.2.0-alpha.2

**Comment by 3zzy** [comment]
@rowanwins Don't think it fixes the issue still, a colleague figured that the tree wasn't being removed correctly so he applied a quick fix and I made a custom build out of that which works fine for now.

https://github.com/jaromirdalecky/turf/commit/4c37a803744016a6accc306983fd82afbb6c1b17

**Comment by 3zzy** [comment]
@rowanwins Speaking of which, building it was an awfully difficult process, would be great if you provide some instructions.

**Comment by Stophface** [comment]
There is still an issue with mask()
https://github.com/Turfjs/turf/issues/2054
