### ISSUE TITLE
buffering near antimeridian above 50 lat

### ISSUE THREAD

**Issue by matthias-ccri** [Turfjs/turf#1847]
Hey guys! I have found what appears to be a bug in `@turf/buffer`.

When buffering shapes close to the antimeridian, so that the buffered feature extends past the antimeridian, the resulting shape is corrupted. The out-of-bounds polygon coordinates get wrapped to the other side of the map. This only happens when the [`needsTransverseMercator` code path](https://github.com/Turfjs/turf/blob/47db2e1f9cf4f67c6cca8eefe4f229e3532046ed/packages/turf-buffer/index.js#L102) kicks in — i.e. when the bbox is above 50 lat.

Here is a gist with input and what I received as output. I ran `turf.buffer(input, 10)` using the version of turf on turfjs.org, using DevTools.

https://gist.github.com/matthias-ccri/8b995c9e0be9c80c481d6a62ab7e7732

![image](https://user-images.githubusercontent.com/18034092/76442105-c9329100-6396-11ea-9624-1f6c91037ef4.png)

![image](https://user-images.githubusercontent.com/18034092/76442141-de0f2480-6396-11ea-813d-78a4df711628.png)

Does this look like a bug in @turf/buffer?

**Comment by matthias-ccri** [comment]
https://github.com/Turfjs/turf/issues/1602 seems related, if this bug is caused by converting the geometry from Transverse Meridian back to WGS84 in `toWgs84`.

**Comment by rowanwins** [comment]
Hi @matthias-ccri 

I believe this is resolved with the v7 alpha release - see this [jsfiddle](https://jsfiddle.net/wq7ge91k/)

The v7 alpha is available via npm
npm install turf@7.0.0-alpha.1

or via cdn
https://unpkg.com/turf@7.0.0-alpha.1/dist/turf.min.js

It's an alpha release so there are few things not quite right but it also fixes a number of bugs

Cheers
Rowan

**Comment by matthias-ccri** [comment]
Thanks Rowan, the v7 buffering looks to be accurate! I can't wait for v7 to land.

I only tested in the northern hemisphere. Surely the southern hemisphere also has the same distortion problems, but the transverseMercator mode only kicks in for shapes > 50 lat. I wonder, why not use the transverseMercator method in all cases?

The transverseMercator method (reprojecting to Transverse Mercator and centering on the shape) seems like the most accurate option so far. Is it being avoided because its slower?

**Comment by matthias-ccri** [comment]
Just checking in on this. `@turf/buffer` 6.5.0, published 2 months ago, doesn't have the fix. We use the `@turf/buffer` package instead of `turf`, so we can't use the v7 prerelease package. Any idea when this fix will make it to the `@turf/buffer` package? Thx

**Comment by gmarshall56** [comment]
It appears to me that the v7 of Turf is not ready.  I have a simple React application that is using this version and uses the [leaflet geoman ](https://github.com/geoman-io/leaflet-geoman) drawing tool.  When I draw a LineString on the map there is a reference error thrown:

![image](https://user-images.githubusercontent.com/5943189/141490673-321c14cd-8328-4d5b-b5d6-568198e0a5c1.png)

Here is the codepen:
https://codepen.io/gmarshall56/pen/xxLaWbr

Further, when I use the same v7 of Turf in my React application - not in a  codepen -  when I draw a line beginning in the northern hemisphere - specifically LA, California, USA down across the equator to and stop in Peru, Turf creates a buffer in the opposite direction.  It appears Turf gets its lat/lng's confused when it has to work across the equator.  See here, the LineString is green and the buffer is red:

![TurfJsV7_NorthSouthLineIssue](https://user-images.githubusercontent.com/5943189/141495405-a10af4a6-f2dc-4fd8-af4c-50bc4c75b539.JPG)

**Comment by smallsaucepan** [comment]
Turf 7 has been released so this should be resolved for you @matthias-ccri, @gmarshall56, @funwhilelost, and @oloompa.

**Comment by matthias-ccri** [comment]
I'm seeing that this issue is still present. Using `@turf/buffer@7.1.0`.

**Comment by smallsaucepan** [comment]
Thanks @matthias-ccri. Is it exactly the same behaviour as originally reported? If not, can you please post your test data and we'll take a look!

**Comment by matthias-ccri** [comment]
Sure thing, here's a codesandbox: https://codesandbox.io/p/sandbox/tyv2sh Same behavior

![image](https://github.com/user-attachments/assets/00851720-57d8-4324-ad0c-73c3b71df332)
