### ISSUE TITLE
Can't install latest version due to Topojson being deprecated

### ISSUE THREAD

**Issue by jose-verissimo** [Turfjs/turf#2077]
No need for a GIST with this error, I'm simply just doing `npm i --save @turf/turf` so it installs the latest version and I get the following error:
```
npm WARN deprecated topojson@3.0.2: Use topojson-client, topojson-server or topojson-simplify directly.
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/jose/Sites/myproject/node_modules/topojson/node_modules/topojson-server/bin/geo2topo
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/jose/Sites/myproject/node_modules/topojson/node_modules/topojson-server/bin/geo2topo'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jose/.npm/_logs/2021-05-05T14_14_00_388Z-debug.log
```
The version I'm trying to install is the latest `v6.3.0`
Node.js version `v14.16.0`

**Comment by levitabris** [comment]
I had the same issue. Downgrading node to v12 _temporarily_ solves it.

**Comment by jose-verissimo** [comment]
> I had the same issue. Downgrading node to v12 _temporarily_ solves it.

Thank you @levitabris that fixed the issue for me _temporarily_!

**Comment by watnotte** [comment]
+1

**Comment by agworkscode** [comment]
It installs for us in one environment (git bash in Windows) and not in another environment (AWS Linux Build).
Both are using NodeJS v12.19.1 (with npm 7.12.0).

**Comment by jose-verissimo** [comment]
@agworkscode The error seems to be:

```
ENOENT: no such file or directory, chmod '/Users/jose/Sites/myproject/node_modules/topojson/node_modules/topojson-server/bin/geo2topo'
```

This could be that it's a command directed at Linux/Mac machines, could explain why the error happens on your AWS Linux Build and not git bash in Windows. The version that I'm using now for it to work in Node.js is `v12.21.0`

**Comment by sdl60660** [comment]
Having this issue too

**Comment by frastlin** [comment]
I'm also having this issue. From my investigation, it looks as if topojson is only used by @turf/concave.
This same problem happened back in February, was there a regression?
https://github.com/Turfjs/turf/issues/2005

I found a reference to this issue for topojson:
https://github.com/topojson/topojson/issues/304

We are running this on multiple opporating systems, and it is working on our windows system, but not on our Linux Heroku server. This error was happening with a windows machine running Node 12, but when it was updated to Node 15, the error was gone. We are using the latest version of npm. I will try downgrading npm to 12, but I think we're using later Node features.

**Comment by levitabris** [comment]
I assume it's a problem with node-gyp on Linux.

**Comment by gokugen** [comment]
Hy,
you just have to install topojson-server (or topojson-client if you are on client side), topojson-simplify before @turf/turf.
Hope it helps someone.

**Comment by robsalasco** [comment]
Would be possible to assign priority to this bug? :(

**Comment by cmoine** [comment]
I had to both:
- downgrade to node 12
- uninstall turf, install topojson-server, then opojson-simplify, and then reinstall turf !
😅

**Comment by LuckyCoders** [comment]
I have same problem and I can't possibilities to downgrade Node in production(((

**Comment by stebogit** [comment]
@LuckyCoders have you tried requiring specifically the topojson packages like suggested above? It does look like that, for some reason, fixes the issue. In my case I did not need to downgrade the Node version.

```node
npm i topojson-client topojson-server topojson-simplify
```

**Comment by Bobvantpadje** [comment]
I'm having the same problem. Even installing `topojson-client topojson-server topojson-simplify` does not work for me. My `package.json` looks like this: 
```
{
  "name": "my-name",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "start": "env-cmd -f .env/dev node src/server.js",
    "start:dev": "env-cmd -f .env/dev node src/server.js",
    "start:test": "env-cmd -f .env/test node src/server.js",
    "start:acc": "env-cmd -f .env/acc node src/server.js"
  },
  "main": "src/server.js",
  "license": "MIT",
  "dependencies": {
    "topojson-server": "^3.0.1",
    "topojson-simplify": "^3.0.3",
    "topojson-client": "^3.1.0",
    "@turf/nearest-point-on-line": "^6.3.0",
    "@turf/turf": "^6.3.0",
    "apollo-datasource-rest": "^0.11.0",
    "apollo-server": "^2.22.2",
    "apollo-server-lambda": "^2.22.2",
    "bluebird": "^3.7.2",
    "graphql": "^15.5.0",
    "https-proxy-agent": "^5.0.0",
    "polyline-encoded": "^0.0.9",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "cross-env": "^7.0.3",
    "env-cmd": "^10.1.0",
    "pkg": "^4.5.1",
    "prettier": "^2.3.0"
  },
  "bin": "src/server.js",
  "pkg": {
    "assets": "datasources/pfx/*"
  }
}

```

**Comment by stebogit** [comment]
@Bobvantpadje I wonder if it has to do with `@turf/turf` library. Try installing only the packages you use

**Comment by Bobvantpadje** [comment]
@stebogit It does seem to be a problem with the `@turf/turf` library. Uninstalling it resolves the error, but this does mean that I can't use the complete functionality of the library.

**Comment by adriankwiat** [comment]
It seems that it is resolved in https://github.com/Turfjs/turf/pull/2037, but not released yet

**Comment by rowanwins** [comment]
This is now resolved in the release of v6.4.0

**Comment by shivenigma** [comment]
I'm using turf 6.4.0 and still getting this error, any idean?
